title: Whatsapp Bulk Sender
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://whatsapp-bulk-sender.github.io

aux_links:
  Template Repository: https://github.com/solutions-guru/whatsapp-bulk-sender-documentation
